const HELLO = 'HELLO'
const ERROR = 'ERROR'

const AUTHENTICATE = 'AUTHENTICATE'
const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS'

const CHECK_CONNECTIONS = 'CHECK_CONNECTIONS'
const CHECK_CONNECTIONS_SUCCESS = 'CHECK_CONNECTIONS_SUCCESS'

module.exports = {
    HELLO, ERROR,
    AUTHENTICATE, AUTHENTICATE_SUCCESS,
    CHECK_CONNECTIONS, CHECK_CONNECTIONS_SUCCESS
}